/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a43e3d257c2286435d4e155cc0219217)
interface __BaseEnv_Env {
	ORIGIN: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
