// Generated by scripts/build-planet-derivatives.mjs. Edit the native masters, not this catalog.
export const PLANET_ART = {
  "terrestrial": {
    "anchor": [
      0.5,
      0.4996012759170654
    ],
    "visualRatio": 0.9393939393939394,
    "levels": [
      {
        "size": 32,
        "url": "/art/derived/planets/2026-09-08/terrestrial-32.png?v=ab77cf584571"
      },
      {
        "size": 64,
        "url": "/art/derived/planets/2026-09-08/terrestrial-64.png?v=37e5fc2f7362"
      },
      {
        "size": 128,
        "url": "/art/derived/planets/2026-09-08/terrestrial-128.png?v=4c3ac35e286b"
      },
      {
        "size": 256,
        "url": "/art/derived/planets/2026-09-08/terrestrial-256.png?v=341f02801d77"
      },
      {
        "size": 512,
        "url": "/art/derived/planets/2026-09-08/terrestrial-512.png?v=de0db197a588"
      },
      {
        "size": 1024,
        "url": "/art/derived/planets/2026-09-08/terrestrial-1024.png?v=094e297c07e7"
      },
      {
        "size": 1254,
        "url": "/art/derived/planets/2026-09-08/terrestrial-1254.png?v=a59a594e4751"
      }
    ]
  },
  "desert": {
    "anchor": [
      0.5,
      0.49681020733652315
    ],
    "visualRatio": 0.9457735247208932,
    "levels": [
      {
        "size": 32,
        "url": "/art/derived/planets/2026-09-08/desert-32.png?v=625d34de26ba"
      },
      {
        "size": 64,
        "url": "/art/derived/planets/2026-09-08/desert-64.png?v=0e4f07fc9117"
      },
      {
        "size": 128,
        "url": "/art/derived/planets/2026-09-08/desert-128.png?v=c91e490fc302"
      },
      {
        "size": 256,
        "url": "/art/derived/planets/2026-09-08/desert-256.png?v=c9422b2e1f75"
      },
      {
        "size": 512,
        "url": "/art/derived/planets/2026-09-08/desert-512.png?v=16197233ff79"
      },
      {
        "size": 1024,
        "url": "/art/derived/planets/2026-09-08/desert-1024.png?v=b290ca6c4830"
      },
      {
        "size": 1254,
        "url": "/art/derived/planets/2026-09-08/desert-1254.png?v=c9ab029ffefa"
      }
    ]
  },
  "ocean": {
    "anchor": [
      0.49920255183413076,
      0.49800637958532695
    ],
    "visualRatio": 0.9457735247208932,
    "levels": [
      {
        "size": 32,
        "url": "/art/derived/planets/2026-09-08/ocean-32.png?v=3fb1f5f07b57"
      },
      {
        "size": 64,
        "url": "/art/derived/planets/2026-09-08/ocean-64.png?v=2be3c0e112ff"
      },
      {
        "size": 128,
        "url": "/art/derived/planets/2026-09-08/ocean-128.png?v=92eea1491220"
      },
      {
        "size": 256,
        "url": "/art/derived/planets/2026-09-08/ocean-256.png?v=861396414067"
      },
      {
        "size": 512,
        "url": "/art/derived/planets/2026-09-08/ocean-512.png?v=c8cbfe2814d5"
      },
      {
        "size": 1024,
        "url": "/art/derived/planets/2026-09-08/ocean-1024.png?v=63dbe86673a6"
      },
      {
        "size": 1254,
        "url": "/art/derived/planets/2026-09-08/ocean-1254.png?v=ab935e48cdb4"
      }
    ]
  },
  "ice": {
    "anchor": [
      0.5007974481658692,
      0.4996012759170654
    ],
    "visualRatio": 0.9441786283891547,
    "levels": [
      {
        "size": 32,
        "url": "/art/derived/planets/2026-09-08/ice-32.png?v=529523ad6a41"
      },
      {
        "size": 64,
        "url": "/art/derived/planets/2026-09-08/ice-64.png?v=921a7cfcb3d6"
      },
      {
        "size": 128,
        "url": "/art/derived/planets/2026-09-08/ice-128.png?v=41d8d0016bc5"
      },
      {
        "size": 256,
        "url": "/art/derived/planets/2026-09-08/ice-256.png?v=678d9223ff18"
      },
      {
        "size": 512,
        "url": "/art/derived/planets/2026-09-08/ice-512.png?v=5fea98adc982"
      },
      {
        "size": 1024,
        "url": "/art/derived/planets/2026-09-08/ice-1024.png?v=5dd7ba36fd01"
      },
      {
        "size": 1254,
        "url": "/art/derived/planets/2026-09-08/ice-1254.png?v=d291755cad04"
      }
    ]
  },
  "gas_giant": {
    "anchor": [
      0.5007974481658692,
      0.49920255183413076
    ],
    "visualRatio": 0.9409888357256778,
    "levels": [
      {
        "size": 32,
        "url": "/art/derived/planets/2026-09-08/gas_giant-32.png?v=7d96dda42308"
      },
      {
        "size": 64,
        "url": "/art/derived/planets/2026-09-08/gas_giant-64.png?v=50b5cbfa3a76"
      },
      {
        "size": 128,
        "url": "/art/derived/planets/2026-09-08/gas_giant-128.png?v=68b8be41f1ce"
      },
      {
        "size": 256,
        "url": "/art/derived/planets/2026-09-08/gas_giant-256.png?v=4e14b61850db"
      },
      {
        "size": 512,
        "url": "/art/derived/planets/2026-09-08/gas_giant-512.png?v=3d3e427f013c"
      },
      {
        "size": 1024,
        "url": "/art/derived/planets/2026-09-08/gas_giant-1024.png?v=922192871c52"
      },
      {
        "size": 1254,
        "url": "/art/derived/planets/2026-09-08/gas_giant-1254.png?v=a779ed012da8"
      }
    ]
  },
  "lava": {
    "anchor": [
      0.4984051036682616,
      0.49760765550239233
    ],
    "visualRatio": 0.9409888357256778,
    "levels": [
      {
        "size": 32,
        "url": "/art/derived/planets/2026-09-08/lava-32.png?v=cef3f9d7e47e"
      },
      {
        "size": 64,
        "url": "/art/derived/planets/2026-09-08/lava-64.png?v=fb29f5b5ee1e"
      },
      {
        "size": 128,
        "url": "/art/derived/planets/2026-09-08/lava-128.png?v=7fb8c0b9964b"
      },
      {
        "size": 256,
        "url": "/art/derived/planets/2026-09-08/lava-256.png?v=ed16e9ace820"
      },
      {
        "size": 512,
        "url": "/art/derived/planets/2026-09-08/lava-512.png?v=8a69a46536cb"
      },
      {
        "size": 1024,
        "url": "/art/derived/planets/2026-09-08/lava-1024.png?v=b6888ae1c98c"
      },
      {
        "size": 1254,
        "url": "/art/derived/planets/2026-09-08/lava-1254.png?v=c4513b31a09e"
      }
    ]
  },
  "barren": {
    "anchor": [
      0.5,
      0.4984051036682616
    ],
    "visualRatio": 0.9425837320574163,
    "levels": [
      {
        "size": 32,
        "url": "/art/derived/planets/2026-09-08/barren-32.png?v=aa3aa1ad17fe"
      },
      {
        "size": 64,
        "url": "/art/derived/planets/2026-09-08/barren-64.png?v=4ebc85bd92c2"
      },
      {
        "size": 128,
        "url": "/art/derived/planets/2026-09-08/barren-128.png?v=41dbd00b5e85"
      },
      {
        "size": 256,
        "url": "/art/derived/planets/2026-09-08/barren-256.png?v=7136a1645a65"
      },
      {
        "size": 512,
        "url": "/art/derived/planets/2026-09-08/barren-512.png?v=0390f2434d9b"
      },
      {
        "size": 1024,
        "url": "/art/derived/planets/2026-09-08/barren-1024.png?v=abd1271ebfe5"
      },
      {
        "size": 1254,
        "url": "/art/derived/planets/2026-09-08/barren-1254.png?v=d688135785cb"
      }
    ]
  },
  "moon": {
    "anchor": [
      0.5,
      0.5
    ],
    "visualRatio": 0.9409888357256778,
    "levels": [
      {
        "size": 32,
        "url": "/art/derived/planets/2026-09-08/moon-32.png?v=1e297f716577"
      },
      {
        "size": 64,
        "url": "/art/derived/planets/2026-09-08/moon-64.png?v=5cef934c489c"
      },
      {
        "size": 128,
        "url": "/art/derived/planets/2026-09-08/moon-128.png?v=99c959ce105b"
      },
      {
        "size": 256,
        "url": "/art/derived/planets/2026-09-08/moon-256.png?v=848e41c35de8"
      },
      {
        "size": 512,
        "url": "/art/derived/planets/2026-09-08/moon-512.png?v=879922f87892"
      },
      {
        "size": 1024,
        "url": "/art/derived/planets/2026-09-08/moon-1024.png?v=5b83ff7cbf2f"
      },
      {
        "size": 1254,
        "url": "/art/derived/planets/2026-09-08/moon-1254.png?v=60e2b12db959"
      }
    ]
  }
} as const;
