// Generated by scripts/build-star-derivatives.mjs. Edit the approved masters, not this catalog.
export const STAR_ART = {
  "galaxy": {
    "red_dwarf": {
      "anchor": [
        0.5059808612440191,
        0.49760765550239233
      ],
      "visualRatio": 0.8413078149920256,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_dwarf-32.png?v=79cdb1ff62f5"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_dwarf-64.png?v=c71709e6ae6b"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_dwarf-128.png?v=5621da629cba"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_dwarf-256.png?v=51e332bb2f07"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_dwarf-512.png?v=29dd0574f98b"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_dwarf-1024.png?v=29414873ef98"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_dwarf-1254.png?v=ebcbf924358b"
        }
      ]
    },
    "yellow_star": {
      "anchor": [
        0.5,
        0.50518341307815
      ],
      "visualRatio": 0.9258373205741627,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/yellow_star-32.png?v=7cf4e1a85303"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/yellow_star-64.png?v=cf71a8c85b1f"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/yellow_star-128.png?v=3018445b2430"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/yellow_star-256.png?v=c5b991e72236"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/yellow_star-512.png?v=4b8ce7438930"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/yellow_star-1024.png?v=caf26d916e78"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/yellow_star-1254.png?v=ff4280e58465"
        }
      ]
    },
    "white_star": {
      "anchor": [
        0.49760765550239233,
        0.4964114832535885
      ],
      "visualRatio": 0.9362041467304625,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_star-32.png?v=94dd4635dcc0"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_star-64.png?v=151a1f136a16"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_star-128.png?v=04bea9fd9783"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_star-256.png?v=9a9d242c6d68"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_star-512.png?v=58f099436a3a"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_star-1024.png?v=0c958a787895"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_star-1254.png?v=79ddde99db9a"
        }
      ]
    },
    "blue_giant": {
      "anchor": [
        0.4984051036682616,
        0.4960127591706539
      ],
      "visualRatio": 0.9106858054226475,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/blue_giant-32.png?v=59a3996e9dfd"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/blue_giant-64.png?v=14a3b73a5c51"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/blue_giant-128.png?v=80a488034f7e"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/blue_giant-256.png?v=d821963869a4"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/blue_giant-512.png?v=cfd277789277"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/blue_giant-1024.png?v=59cd2849c0ad"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/blue_giant-1254.png?v=3904a8bb6e3d"
        }
      ]
    },
    "red_giant": {
      "anchor": [
        0.49242424242424243,
        0.49800637958532695
      ],
      "visualRatio": 0.7854864433811802,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_giant-32.png?v=4b2f642874ae"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_giant-64.png?v=522201662fd1"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_giant-128.png?v=1868e8351887"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_giant-256.png?v=a5b9306dc0a3"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_giant-512.png?v=0c537d4df13a"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_giant-1024.png?v=333411f9ecb0"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/red_giant-1254.png?v=3e6ed0ab7d4f"
        }
      ]
    },
    "white_dwarf": {
      "anchor": [
        0.5007974481658692,
        0.49920255183413076
      ],
      "visualRatio": 0.8947368421052632,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_dwarf-32.png?v=b8fc472cfee3"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_dwarf-64.png?v=5be1006b9093"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_dwarf-128.png?v=8ce1267fea5c"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_dwarf-256.png?v=120e6494c698"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_dwarf-512.png?v=286bf1272b5d"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_dwarf-1024.png?v=e2faae22e445"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/white_dwarf-1254.png?v=966034a2099c"
        }
      ]
    },
    "neutron_star": {
      "anchor": [
        0.5015948963317385,
        0.4996012759170654
      ],
      "visualRatio": 0.9346092503987241,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/neutron_star-32.png?v=e3a773fd02c0"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/neutron_star-64.png?v=3ce86003e743"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/neutron_star-128.png?v=e79d3340f516"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/neutron_star-256.png?v=83a0456a748b"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/neutron_star-512.png?v=c807623f2822"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/neutron_star-1024.png?v=551597402c6d"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/neutron_star-1254.png?v=c8c3d1a7e456"
        }
      ]
    },
    "binary_star": {
      "anchor": [
        0.5115629984051037,
        0.5123604465709729
      ],
      "visualRatio": 0.7137161084529505,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/binary_star-32.png?v=f67abb711cab"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/binary_star-64.png?v=41b7ee2276aa"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/binary_star-128.png?v=175f5389ab27"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/binary_star-256.png?v=b96476c1d920"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/binary_star-512.png?v=55a16e88fcee"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/binary_star-1024.png?v=ac03cbc75716"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/binary_star-1254.png?v=8a830399d5cd"
        }
      ]
    },
    "black_hole": {
      "anchor": [
        0.5027910685805422,
        0.4892344497607656
      ],
      "visualRatio": 0.9497607655502392,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/black_hole-32.png?v=0d2c56d27859"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/black_hole-64.png?v=9acd215eca49"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/black_hole-128.png?v=83fb07abf762"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/black_hole-256.png?v=9379eb8a0525"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/black_hole-512.png?v=c89551f319cb"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/black_hole-1024.png?v=39382896d245"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/black_hole-1254.png?v=1a9fdd455b02"
        }
      ]
    },
    "magnetar": {
      "anchor": [
        0.5,
        0.4932216905901116
      ],
      "visualRatio": 0.9146730462519936,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/galaxy/magnetar-32.png?v=4a0bd96f97e5"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/galaxy/magnetar-64.png?v=0ae24d752a6d"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/galaxy/magnetar-128.png?v=71870ef033e9"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/galaxy/magnetar-256.png?v=9ced21fc3497"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/galaxy/magnetar-512.png?v=764f232a8cb8"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/galaxy/magnetar-1024.png?v=ae9e0607a4dc"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/galaxy/magnetar-1254.png?v=c3da988cfda2"
        }
      ]
    }
  },
  "system": {
    "red_dwarf": {
      "anchor": [
        0.5,
        0.4904306220095694
      ],
      "visualRatio": 0.8149920255183413,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/red_dwarf-32.png?v=53d4ea991c5e"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/red_dwarf-64.png?v=4dbbf724ac24"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/red_dwarf-128.png?v=1536dd55feaa"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/red_dwarf-256.png?v=4039f0d4e07a"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/red_dwarf-512.png?v=c68993457624"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/red_dwarf-1024.png?v=38e98c4a81d6"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/red_dwarf-1254.png?v=3298ebcdaff9"
        }
      ]
    },
    "yellow_star": {
      "anchor": [
        0.49920255183413076,
        0.49401913875598086
      ],
      "visualRatio": 0.8748006379585327,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/yellow_star-32.png?v=3aad02b55963"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/yellow_star-64.png?v=320cabe45c25"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/yellow_star-128.png?v=c64c4c6b7632"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/yellow_star-256.png?v=7a3e8042a256"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/yellow_star-512.png?v=84a62eb665af"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/yellow_star-1024.png?v=ac36753e8300"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/yellow_star-1254.png?v=127a74cb8562"
        }
      ]
    },
    "white_star": {
      "anchor": [
        0.5011961722488039,
        0.5
      ],
      "visualRatio": 0.8636363636363636,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/white_star-32.png?v=ed6343cb2227"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/white_star-64.png?v=89d51314b66d"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/white_star-128.png?v=f72b65b5312e"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/white_star-256.png?v=2a9dc887eb52"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/white_star-512.png?v=d6f68d0e71b4"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/white_star-1024.png?v=b1d796f86db3"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/white_star-1254.png?v=dbdba8ce271d"
        }
      ]
    },
    "blue_giant": {
      "anchor": [
        0.507177033492823,
        0.49362041467304624
      ],
      "visualRatio": 0.8484848484848485,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/blue_giant-32.png?v=1182a0f548b3"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/blue_giant-64.png?v=80ee3db01a17"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/blue_giant-128.png?v=83e7b20228a4"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/blue_giant-256.png?v=9bfc7246e1b9"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/blue_giant-512.png?v=ba3525f5dbff"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/blue_giant-1024.png?v=8a40d3a33a4b"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/blue_giant-1254.png?v=d1d04defc719"
        }
      ]
    },
    "red_giant": {
      "anchor": [
        0.5087719298245614,
        0.4892344497607656
      ],
      "visualRatio": 0.9425837320574163,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/red_giant-32.png?v=c61433f75def"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/red_giant-64.png?v=9dd298a4bde0"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/red_giant-128.png?v=a5b1a0327eef"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/red_giant-256.png?v=7fdc0f17d5f1"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/red_giant-512.png?v=67010c2302de"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/red_giant-1024.png?v=c0f45bb4ca10"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/red_giant-1254.png?v=8f8e07e07ad8"
        }
      ]
    },
    "white_dwarf": {
      "anchor": [
        0.5,
        0.4988038277511962
      ],
      "visualRatio": 0.6299840510366826,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/white_dwarf-32.png?v=6f550e1491f3"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/white_dwarf-64.png?v=2f9646d6eaca"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/white_dwarf-128.png?v=2a378d5ee0da"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/white_dwarf-256.png?v=9045383c5990"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/white_dwarf-512.png?v=efd2fc4e9d43"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/white_dwarf-1024.png?v=b87def116e28"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/white_dwarf-1254.png?v=99adb0fef622"
        }
      ]
    },
    "neutron_star": {
      "anchor": [
        0.5219298245614035,
        0.5043859649122807
      ],
      "visualRatio": 0.9178628389154705,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/neutron_star-32.png?v=703c8d2ad883"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/neutron_star-64.png?v=7cdcc75ddc69"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/neutron_star-128.png?v=0578b09c1e57"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/neutron_star-256.png?v=8922e974610e"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/neutron_star-512.png?v=4cfd8215a4b3"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/neutron_star-1024.png?v=b5c2b2c72e95"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/neutron_star-1254.png?v=1430ef77d2b7"
        }
      ]
    },
    "binary_star": {
      "anchor": [
        0.4996012759170654,
        0.5035885167464115
      ],
      "visualRatio": 0.9274322169059012,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/binary_star-32.png?v=00d598ec362d"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/binary_star-64.png?v=afbb37167758"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/binary_star-128.png?v=fb5bec289d31"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/binary_star-256.png?v=7f2c79ce2fd6"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/binary_star-512.png?v=3e735b19f52b"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/binary_star-1024.png?v=2f7bbac09ce4"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/binary_star-1254.png?v=dd0d31185307"
        }
      ]
    },
    "black_hole": {
      "anchor": [
        0.4996012759170654,
        0.4748803827751196
      ],
      "visualRatio": 0.9625199362041468,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/black_hole-32.png?v=3b98bcb568ed"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/black_hole-64.png?v=cdfafc11c30e"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/black_hole-128.png?v=0bf3f71f3624"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/black_hole-256.png?v=c8da56879844"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/black_hole-512.png?v=4b153e22d275"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/black_hole-1024.png?v=1e909ab6af0f"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/black_hole-1254.png?v=7e5c0e346827"
        }
      ]
    },
    "magnetar": {
      "anchor": [
        0.5,
        0.5023923444976076
      ],
      "visualRatio": 0.8452950558213717,
      "levels": [
        {
          "size": 32,
          "url": "/art/derived/stars/2026-09-08/system/magnetar-32.png?v=3f1128f55f24"
        },
        {
          "size": 64,
          "url": "/art/derived/stars/2026-09-08/system/magnetar-64.png?v=cf84f7fb04cc"
        },
        {
          "size": 128,
          "url": "/art/derived/stars/2026-09-08/system/magnetar-128.png?v=44d74f9eebf5"
        },
        {
          "size": 256,
          "url": "/art/derived/stars/2026-09-08/system/magnetar-256.png?v=d2ecdf42020b"
        },
        {
          "size": 512,
          "url": "/art/derived/stars/2026-09-08/system/magnetar-512.png?v=2eb49fff9142"
        },
        {
          "size": 1024,
          "url": "/art/derived/stars/2026-09-08/system/magnetar-1024.png?v=4af3f286cf30"
        },
        {
          "size": 1254,
          "url": "/art/derived/stars/2026-09-08/system/magnetar-1254.png?v=34c7b2a6ec8c"
        }
      ]
    }
  }
} as const;
